export const type = {
  RESET_FORM: "RESET_FORM",
  ADD_COMMENTS: "ADD_COMMENTS",
  COMMENTS_FAILED: "COMMENTS_FAILED",
  LEADERS_LOADING: "LEADERS_LOADING",
  ADD_LEADERS: "ADD_LEADERS",
  LEADERS_FAILED: "LEADERS_FAILED",
  PROMO_LOADING: "PROMO_LOADING",
  ADD_PROMOTIONS: "ADD_PROMOTIONS",
  PROMO_FAILED: "PROMO_FAILED",
  DISHES_LOADING: "DISHES_LOADING",
  ADD_DISHES: "ADD_DISHES",
  DISHES_FAILED: "DISHES_FAILED",
};
