export const type = {
  SET_COMMENTS: "SET_COMMENTS",
  SET_LEADERS: "SET_LEADERS",
  SET_PROMOTIONS: "SET_PROMOTIONS",
  DISHES_LOADING: "DISHES_LOADING",
  DISHES_FIALED: "DISHES_FAILED",
  SET_DISHES: "SET_DISHES",
};
